<?
/**
 * @name         Push Out Post
 * @version      1.0
 * @package      pop
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.0308
 */


$conf['mod_pop_name']         = _t("Outbound Email");
$conf['mod_pop_menuorder']    = 84;
$conf['mod_pop_dependencies'] = "";
$conf['mod_pop_version']      = 1.0;
