<?php
/**This is the config file for the OR module, specifies configuration
*  settings
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author     Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
* @package    sahana
* @subpackage or
*/

// provide the nice display name for the OR  module
$conf['mod_itag_name'] = _t("Image Tagger");
$conf['mod_itag_menuorder'] = 4; 


