INSERT INTO `field_options` (`field_name`, `option_code`, `option_description`) VALUES
('opt_group_type', 'fam', 'family'),
('opt_group_type', 'com', 'company'),
('opt_group_type', 'soc', 'society'),
('opt_group_type', 'tor', 'tourists'),
('opt_group_type', 'oth', 'other'),
('opt_group_type', '===', '==Select Option=='),
('opt_id_type', 'nic', 'National Identity Card'),
('opt_id_type', 'pas', 'Passport'),
('opt_id_type', 'dln', 'Driving License Number'),
('opt_id_type', 'oth', 'Other'),
('opt_status', 'ali', 'Alive & Well'),
('opt_status', 'mis', 'Missing'),
('opt_status', 'inj', 'Injured'),
('opt_status', 'dec', 'Deceased'),
('opt_gender', 'mal', 'Male'),
('opt_gender', 'fml', 'Female'),
('opt_relationship_type', 'fat', 'Father'),
('opt_relationship_type', 'mot', 'Mother'),
('opt_relationship_type', 'bro', 'Brother'),
('opt_relationship_type', 'sis', 'Sister'),
('opt_relationship_type', 'gft', 'GrandFather'),
('opt_relationship_type', 'gmt', 'GrandMother'),
('opt_relationship_type', 'gfpat', 'GrandFatherPaternal'),
('opt_relationship_type', 'gfmat', 'GrandFatherMaternal'),
('opt_relationship_type', 'gmpat', 'GrandMotherPaternal'),
('opt_relationship_type', 'gmmat', 'GrandMotherMaternal'),
('opt_relationship_type', 'fnd', 'Friend'),
('opt_relationship_type', 'oth', 'Other'),
('opt_contact_type', 'home', 'Home(permanent address)'),
('opt_contact_type', 'name', 'Contact Person'),
('opt_contact_type', 'pmob', 'Personal Mobile'),
('opt_contact_type', 'curr', 'Current Phone'),
('opt_contact_type', 'cmob', 'Current Mobile'),
('opt_contact_type', 'emai', 'Email address'),
('opt_contact_type', 'fax', 'Fax Number'),
('opt_contact_type', 'web', 'Website'),
('opt_contact_type', 'inst', 'Instant Messenger'),
('opt_person_loc_type', 'hom', 'Permanent home address)'),
('opt_person_loc_type', 'imp', 'Impact location'),
('opt_person_loc_type', 'cur', 'Current location'),
('opt_age_group', 'unk', 'Unknown'),
('opt_age_group', 'inf', 'Infant (0-1)'),
('opt_age_group', 'chi', 'Child (1-15)'),
('opt_age_group', 'you', 'Young Adult (16-21)'),
('opt_age_group', 'adu', 'Adult (22-50)'),
('opt_age_group', 'sen', 'Senior Citizen (50+)'),
('opt_country', 'uk', 'United Kingdom'),
('opt_country', 'lanka', 'Sri Lanka'),
('opt_race', 'unk', 'Unknown'),
('opt_race', 'filip', 'Filipino'),
('opt_race', 'other', 'Other'),
('opt_religion', 'unk', 'Unknown'),
('opt_religion', 'bud', 'Buddhist'),
('opt_religion', 'chr', 'Christian'),
('opt_religion', 'mus', 'Muslim'),
('opt_religion', 'oth', 'Other'),
('opt_marital_status', 'unk', 'Unknown'),
('opt_marital_status', 'sin', 'Single'),
('opt_marital_status', 'mar', 'Married'),
('opt_marital_status', 'div', 'Divorced'),
('opt_blood_type', 'unk', 'Unknown'),
('opt_blood_type', 'a+', 'A+'),
('opt_blood_type', 'a-', 'A-'),
('opt_blood_type', 'b+', 'B+'),
('opt_blood_type', 'b-', 'B-'),
('opt_blood_type', 'ab+', 'AB+'),
('opt_blood_type', 'ab-', 'AB-'),
('opt_blood_type', 'o+', 'O+'),
('opt_blood_type', 'o-', 'O-'),
('opt_blood_type', 'oth', 'Other'),
('opt_eye_color', 'unk', 'Unknown'),
('opt_eye_color', 'bla', 'Black'),
('opt_eye_color', 'bro', 'Light Brown'),
('opt_eye_color', 'blu', 'Blue'),
('opt_eye_color', 'oth', 'Other'),
('opt_skin_color', 'unk', 'Unknown'),
('opt_skin_color', 'bla', 'Black'),
('opt_skin_color', 'bro', 'Dark Brown'),
('opt_skin_color', 'fai', 'Fair'),
('opt_skin_color', 'whi', 'White'),
('opt_skin_color', 'oth', 'Other'),
('opt_hair_color', 'unk', 'Unknown'),
('opt_hair_color', 'bla', 'Black'),
('opt_hair_color', 'bro', 'Brown'),
('opt_hair_color', 'red', 'Red'),
('opt_hair_color', 'blo', 'Blond'),
('opt_hair_color', 'oth', 'Other'),
('opt_camp_type', 'ngo', 'NGO Run Camp'),
('opt_camp_type', 'tmp', 'Temporary Shelter'),
('opt_camp_type', 'gov', 'Government Evacuation Center'),
('opt_camp_service', 'adm', 'Administrative Facilities'),
('opt_camp_service', 'snt', 'Sanitation Facilities'),
('opt_camp_service', 'wat', 'Water Facilities'),
('opt_camp_service', 'mdc', 'Medical Facilities'),
('opt_org_type', 'gov', 'Government'),
('opt_org_type', 'priv', 'Private'),
('opt_org_type', 'ngo', 'NGO'),
('opt_org_type', 'ingo', 'International NGO'),
('opt_org_type', 'mngo', 'Multinational NGO'),
('opt_org_sub_type', 'dep', 'Department'),
('opt_org_sub_type', 'subs', 'Subsidiary'),
('opt_org_sub_type', 'bra', 'Branch'),
('opt_sector_type', 'sup', 'Supplier of Goods'),
('opt_sector_type', 'comm', 'Communications'),
('opt_sector_type', 'med', 'Medical Services'),
('opt_sector_type', 'rehab', 'Rehabilitation'),
('opt_sector_type', 'edu', 'Education'),
('opt_location_type', '1', 'Country'),
('opt_location_type', '2', 'State'),
('opt_location_type', '3', 'City'),
('opt_cs_depth', '6', 'depth'),
('opt_cs_page_record', '30', 'number of page records'),
('opt_rs_rep_freq', '30', 'the frequency of report update'),
('opt_rs_cht_freq', '30', 'the frequency of chart update'),
('opt_landmark_type', 'vil', 'Village'),
('opt_landmark_type', 'tem', 'Temple'),
('opt_landmark_type', 'sch', 'School'),
('opt_landmark_contact_type', 'cor', 'Coordinator'),
('opt_landmark_contact_type', 'cof', 'Chief Of Village'),
('opt_landmark_contact_type', 'mon', 'Monk'),
('opt_wikimap_type', 'gen', 'General'),
('opt_wikimap_type', 'per', 'Person Status'),
('opt_wikimap_type', 'dam', 'Damage Status'),
('opt_wikimap_type', 'dis', 'Disaster Status'),
('opt_wikimap_type', 'sos', 'Help Needed'),
('opt_contact_type', 'emphone', 'Emergency Phone Contact'),
('opt_skill_type', 'ANI2', 'General Skills-Animals-Animal Control Vehicles'),
('opt_skill_type', 'ANI1', 'General Skills-Animals-Animal Handling'),
('opt_skill_type', 'ANI3', 'General Skills-Animals-Grief Counseling'),
('opt_skill_type', 'ANI4', 'General Skills-Animals-Horse Trailers'),
('opt_skill_type', 'ANI5', 'General Skills-Animals-Livestock Vehicles'),
('opt_skill_type', 'ANI8', 'General Skills-Animals-Other'),
('opt_skill_type', 'ANI7', 'General Skills-Animals-Veterinarian'),
('opt_skill_type', 'ANI6', 'General Skills-Animals-Veterinary Technician'),
('opt_skill_type', 'AUT2', 'General Skills-Automotive-Body Repair'),
('opt_skill_type', 'AUT1', 'General Skills-Automotive-Engine Repair'),
('opt_skill_type', 'AUT3', 'General Skills-Automotive-Lights, Electrical'),
('opt_skill_type', 'AUT6', 'General Skills-Automotive-Other'),
('opt_skill_type', 'AUT4', 'General Skills-Automotive-Tire Repair'),
('opt_skill_type', 'AUT5', 'General Skills-Automotive-Wheel and Brake Repair'),
('opt_skill_type', 'BAB1', 'General Skills-Baby and Child Care-Aide'),
('opt_skill_type', 'BAB2', 'General Skills-Baby and Child Care-Leader'),
('opt_skill_type', 'BAB3', 'General Skills-Baby and Child Care-Other'),
('opt_skill_type', 'CON1', 'General Skills-Construction Services-Glass Service'),
('opt_skill_type', 'CON2', 'General Skills-Construction Services-House Repair'),
('opt_skill_type', 'CON3', 'General Skills-Construction Services-Inspection, B'),
('opt_skill_type', 'CON6', 'General Skills-Construction Services-Other'),
('opt_skill_type', 'CON4', 'General Skills-Construction Services-Roofing'),
('opt_skill_type', 'CON5', 'General Skills-Construction Services-Window Repair'),
('opt_skill_type', 'ELE1', 'General Skills-Electrical-External Wiring'),
('opt_skill_type', 'ELE2', 'General Skills-Electrical-Internal Wiring'),
('opt_skill_type', 'ELE3', 'General Skills-Electrical-Other'),
('opt_skill_type', 'FOO1', 'General Skills-Food Service-Cooking'),
('opt_skill_type', 'FOO2', 'General Skills-Food Service-Directing'),
('opt_skill_type', 'FOO5', 'General Skills-Food Service-Other'),
('opt_skill_type', 'FOO3', 'General Skills-Food Service-Preparing'),
('opt_skill_type', 'FOO4', 'General Skills-Food Service-Serving'),
('opt_skill_type', 'HAZ1', 'General Skills-Hazardous Materials-Asbestos'),
('opt_skill_type', 'HAZ2', 'General Skills-Hazardous Materials-Chemicals'),
('opt_skill_type', 'HAZ3', 'General Skills-Hazardous Materials-Explosives'),
('opt_skill_type', 'HAZ4', 'General Skills-Hazardous Materials-Flammables'),
('opt_skill_type', 'HAZ5', 'General Skills-Hazardous Materials-Gases'),
('opt_skill_type', 'HAZ6', 'General Skills-Hazardous Materials-Identification'),
('opt_skill_type', 'HAZ8', 'General Skills-Hazardous Materials-Other'),
('opt_skill_type', 'HAZ7', 'General Skills-Hazardous Materials-Radioactive '),
('opt_skill_type', 'INF1', 'General Skills-Information Services-Book Restorati'),
('opt_skill_type', 'INF2', 'General Skills-Information Services-Computer'),
('opt_skill_type', 'INF3', 'General Skills-Information Services-Data Entry'),
('opt_skill_type', 'INF4', 'General Skills-Information Services-Hardware (Comp'),
('opt_skill_type', 'INF7', 'General Skills-Information Services-Other'),
('opt_skill_type', 'INF5', 'General Skills-Information Services-Software (Comp'),
('opt_skill_type', 'INF6', 'General Skills-Information Services-Telephone Repa'),
('opt_skill_type', 'MED1', 'General Skills-Medical-Assist to Physician'),
('opt_skill_type', 'MED2', 'General Skills-Medical-Counseling'),
('opt_skill_type', 'MED3', 'General Skills-Medical-Dentist'),
('opt_skill_type', 'MED4', 'General Skills-Medical-First Aid'),
('opt_skill_type', 'MED5', 'General Skills-Medical-Medical, Ambulance'),
('opt_skill_type', 'MED6', 'General Skills-Medical-Nurse'),
('opt_skill_type', 'MED9', 'General Skills-Medical-Other'),
('opt_skill_type', 'MED7', 'General Skills-Medical-Physician'),
('opt_skill_type', 'MED8', 'General Skills-Medical-Technician'),
('opt_skill_type', 'PLU2', 'General Skills-Plumbing-Other'),
('opt_skill_type', 'PLU1', 'General Skills-Plumbing-Pumping-With Pump'),
('opt_skill_type', 'PLU3', 'General Skills-Plumbing-Pumping-Without Pump'),
('opt_skill_type', 'TRE1', 'General Skills-Tree-Evaluation of Needs'),
('opt_skill_type', 'TRE4', 'General Skills-Tree-Other'),
('opt_skill_type', 'TRE2', 'General Skills-Tree-Removal of Trees'),
('opt_skill_type', 'TRE3', 'General Skills-Tree-Trimming of Trees'),
('opt_skill_type', 'UNS1', 'Unskilled-Other-Baby Care Help'),
('opt_skill_type', 'UNS2', 'Unskilled-Other-Clerical'),
('opt_skill_type', 'UNS3', 'Unskilled-Other-Food Help'),
('opt_skill_type', 'UNS4', 'Unskilled-Other-Heavy Labor (Moving, Erecting Tent'),
('opt_skill_type', 'UNS5', 'Unskilled-Other-Light Labor (Cleanup)'),
('opt_skill_type', 'UNS6', 'Unskilled-Other-Messenger (Local People Preferred)'),
('opt_skill_type', 'UNS7', 'Unskilled-Other-Miscellaneous'),
('opt_skill_type', 'VEH1', 'Resources-Vehicle-Own Aircraft'),
('opt_skill_type', 'VEH5', 'Resources-Building Aide-Own Backhoe'),
('opt_skill_type', 'VEH2', 'Resources-Building Aide-Own Bulldozer'),
('opt_skill_type', 'VEH3', 'Resources-Building Aide-Own Crane'),
('opt_skill_type', 'VEH4', 'Resources-Building Aide-Own Forklift'),
('opt_skill_type', 'VEH7', 'Resources-Building Aide-Own Heavy Equipment'),
('opt_skill_type', 'VEH6', 'Resources-Vehicle-Own Medical; Ambulance'),
('opt_skill_type', 'VEH13', 'Resources-Vehicle-Own Other'),
('opt_skill_type', 'VEH8', 'Resources-Vehicle-Own Refrigerated'),
('opt_skill_type', 'VEH9', 'Resources-Vehicle-Own Steamshovel'),
('opt_skill_type', 'VEH10', 'Resources-Vehicle-Own Truck'),
('opt_skill_type', 'VEH11', 'Resources-Vehicle-Own Van, Car'),
('opt_skill_type', 'VEH12', 'Resources-Vehicle-Own Boat(s)'),
('opt_skill_type', 'WAR1', 'Resources-Warehouse-Forklift'),
('opt_skill_type', 'WAR2', 'Resources-Warehouse-General'),
('opt_skill_type', 'WAR3', 'General Skills-Warehouse-Management'),
('opt_skill_type', 'WIT1', 'Unskilled-With Tools-with Brooms'),
('opt_skill_type', 'WIT2', 'Unskilled-With Tools-with Carpentry Tools'),
('opt_skill_type', 'WIT7', 'Unskilled-With Tools-with Other Tools'),
('opt_skill_type', 'WIT3', 'Unskilled-With Tools-with Pump, Small'),
('opt_skill_type', 'WIT4', 'Unskilled-With Tools-with Saws, Chainsaw'),
('opt_skill_type', 'WIT5', 'Unskilled-With Tools-with Wheelbarrow'),
('opt_skill_type', 'WIT6', 'Unskilled-With Tools-with Yard Tools'),
('opt_skill_type', 'REST1', 'Restriction-No Heavy Lifting'),
('opt_skill_type', 'REST2', 'Restriction-Can not drive'),
('opt_skill_type', 'REST1', 'Restriction-No Heavy Lifting'),
('opt_skill_type', 'REST2', 'Restriction-Can not drive'),
('opt_skill_type', 'REST3', 'Restriction-Can not swim'),
('opt_skill_type', 'REST4', 'Restriction-Handicapped'),
('opt_skill_type', 'MGR', 'Site Manager'),
('opt_addr_type', 'adtyphy', 'Physical'),
('opt_contact_mode', 'email', 'Email'),
('opt_loc_health_type', 'olhtnat', 'National'),
('opt_loc_health_type', 'olhtreg', 'Regional'),
('opt_loc_health_type', 'olhtprov', 'Province'),
('opt_loc_health_type', 'olhtdist', 'District'),
('opt_loc_health_type', 'olhtdiv', 'Division'),
('opt_gender', 'unk', 'Unknown'),
('opt_contact_mode', 'hmp', 'Home Telephone'),
('opt_contact_mode', 'offp', 'Office Telephone'),
('opt_contact_mode', 'fax', 'Fascismile'),
('opt_contact_mode', 'mp', 'Mobile Phone'),
('opt_addr_type', 'adtybill', 'Billing'),
('opt_contact_mode', 'web', 'Website'),
('opt_addr_type', 'adtymail', 'Mailling'),
('opt_contact_mode', 'blog', 'Blog'),
('opt_contact_mode', 'pager', 'Pager'),
('opt_contact_mode', 'im', 'Instant Messenger'),
('opt_addr_type', 'adtytemp', 'Temporary'),
('opt_addr_type', 'adtyoff', 'Office'),
('opt_addr_status', 'adstact', 'Active'),
('opt_addr_status', 'adstina', 'Inactive'),
('opt_addr_status', 'adstfut', 'Future'),
('opt_addr_status', 'adstunk', 'Unknown'),
('opt_fac_status', 'fcstor', 'Operational'),
('opt_fac_status', 'fcstcl', 'Closed'),
('opt_fac_status', 'fcston', 'Opened'),
('opt_fac_status', 'fcstunk', 'Unknown'),
('opt_dis_priority', 'disph', 'High'),
('opt_dis_priority', 'dispm', 'Medium'),
('opt_dis_priority', 'displ', 'Low'),
('opt_shape', 'shpply', 'Polygon'),
('opt_shape', 'shpcir', 'Circle'),
('opt_shape', 'shptri', 'Triangle'),
('opt_shape', 'shprec', 'Rectangle'),
('opt_shape', 'shppt', 'Point'),
('opt_shape', 'shpln', 'Line'),
('opt_addr_elmnt', 'adelcntry', 'Country'),
('opt_addr_elmnt', 'adelprov', 'Province'),
('opt_addr_elmnt', 'adeldist', 'District'),
('opt_addr_elmnt', 'adelvil', 'Village'),
('opt_addr_elmnt', 'adeltwn', 'Town'),
('opt_addr_elmnt', 'adelState', 'State'),
('opt_addr_elmnt', 'adelState', 'State');

-- Priority
INSERT INTO `field_options` (`field_name`,`option_code`,`option_description`) VALUES
('opt_dis_priority', 'low', 'Low'),
('opt_dis_priority', 'medium', 'Medium'),
('opt_dis_priority', 'high', 'High');

-- Shape
INSERT INTO `field_options` (`field_name`,`option_code`,`option_description`) VALUES
('opt_shape', 'poly', 'Point'),
('opt_shape', 'test', 'Line'),
('opt_shape', 'poly', 'Triangle'),
('opt_shape', 'poly', 'Rectangle'),
('opt_shape', 'poly', 'Circle'),
('opt_shape', 'poly', 'Polygon');
