<?php
/**
* Description for file
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @package    Sahana - http://sahana.sourceforge.net
* @author     Sudheera R. Fernando <sudheera@opensource.lk>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
*/ 

global $global;
require_once('lib_rms.inc');

_shn_rms_show_headder(_("Home Page"));

//$user_id = $global['person_id'];
//$org_id = $global['org_id'];
//
//$req_count = count_req();
//$user_req_count = count_user_req($user_id);
//$org_req_count = count_user_req($org_id);
//$org_reqff_count = count_user_reqff($user_id);
//$user_oreq_count = count_user_reqstat($user_id,'open');
//$user_creq_count = count_user_reqstat($user_id,'closed');
?>
<h2>The Request Management System tracks all requests and helps match pledges for support,<br/><br/> aid and supplies to fullfilment</h2>
