
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI1', 'ANIMALS  -  Animal Handling');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI2', 'ANIMALS  -  Animal Control Vehicles');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI3', 'ANIMALS  -  Grief Counseling');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI4', 'ANIMALS  -  Horse Trailers');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI5', 'ANIMALS  -  Livestock Vehicles');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI6', 'ANIMALS  -  Veterinary Technician');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI7', 'ANIMALS  -  Veterinarian');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ANI8', 'ANIMALS  -  Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'AUT1', 'AUTOMOTIVE  Skilled - Engine Repair');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'AUT2', 'AUTOMOTIVE  Skilled - Body Repair');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'AUT3', 'AUTOMOTIVE  Skilled - Lights, Electrical');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'AUT4', 'AUTOMOTIVE  Skilled - Tire Repair');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'AUT5', 'AUTOMOTIVE  Skilled - Wheel and Brake Repair');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'AUT6', 'AUTOMOTIVE  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'BAB1', 'BABY AND CHILD CARE  Skilled - Aide');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'BAB2', 'BABY AND CHILD CARE  Skilled - Leader');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'BAB3', 'BABY AND CHILD CARE  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'CON1', 'CONSTRUCTION SERVICES  -  Glass Services');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'CON2', 'CONSTRUCTION SERVICES  -  House Repair');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'CON3', 'CONSTRUCTION SERVICES  -  Inspection, Buildings');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'CON4', 'CONSTRUCTION SERVICES  -  Roofing');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'CON5', 'CONSTRUCTION SERVICES  -  Window Repair');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'CON6', 'CONSTRUCTION SERVICES  -  Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ELE1', 'ELECTRICAL  Skilled - External Wiring');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ELE2', 'ELECTRICAL  Skilled - Internal Wiring');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'ELE3', 'ELECTRICAL  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'FOO1', 'FOOD SERVICE  Skilled - Cooking');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'FOO2', 'FOOD SERVICE  Skilled - Directing');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'FOO3', 'FOOD SERVICE  Skilled - Preparing');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'FOO4', 'FOOD SERVICE  Skilled - Serving');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'FOO5', 'FOOD SERVICE  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ1', 'HAZARDOUS MATERIALS  Skilled - Asbestos');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ2', 'HAZARDOUS MATERIALS  Skilled - Chemicals');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ3', 'HAZARDOUS MATERIALS  Skilled - Explosives');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ4', 'HAZARDOUS MATERIALS  Skilled - Flammables');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ5', 'HAZARDOUS MATERIALS  Skilled - Gases');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ6', 'HAZARDOUS MATERIALS  Skilled - Identification of');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ7', 'HAZARDOUS MATERIALS  Skilled - Radioactive');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'HAZ8', 'HAZARDOUS MATERIALS  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'INF1', 'INFORMATION SERVICES  Skilled - Book Restoration');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'INF2', 'INFORMATION SERVICES  Skilled - Computer');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'INF3', 'INFORMATION SERVICES  Skilled - Data Entry');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'INF4', 'INFORMATION SERVICES  Skilled - Hardware - Compute');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'INF5', 'INFORMATION SERVICES  Skilled - Software - Compute');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'INF6', 'INFORMATION SERVICES  Skilled - Telephone Repair');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'INF7', 'INFORMATION SERVICES  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED1', 'MEDICAL  Skilled - Assist to Physician');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED2', 'MEDICAL  Skilled - Counseling');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED3', 'MEDICAL  Skilled - Dentist');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED4', 'MEDICAL  Skilled - First Aid');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED5', 'MEDICAL  Skilled - Medical, Ambulance');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED6', 'MEDICAL  Skilled - Nurse');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED7', 'MEDICAL  Skilled - Physician');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED8', 'MEDICAL  Skilled - Technician');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'MED9', 'MEDICAL  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'PLU1', 'PLUMBING  Skilled - Pumping -With Pump');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'PLU2', 'PLUMBING  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'TRE1', 'TREE  Skilled - Evaluation of Needs');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'TRE2', 'TREE  Skilled - Removal of Trees');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'TRE3', 'TREE  Skilled - Trimming of Trees');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'TRE4', 'TREE  Skilled - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'UNS1', 'UNSKILLED - Baby Care Help');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'UNS2', 'UNSKILLED - Clerical');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'UNS3', 'UNSKILLED - Food Help');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'UNS4', 'UNSKILLED - Heavy Labor -Moving, Erecting Tents');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'UNS5', 'UNSKILLED - Light Labor -Cleanup-');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'UNS6', 'UNSKILLED - Messanger -Local People Preffered');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'UNS7', 'UNSKILLED - Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH1', 'VEHICLE - Own  Aircraft');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH10', 'VEHICLE - Own  Truck');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH11', 'VEHICLE - Own  Van, Car');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH12', 'VEHICLE - Own  Water Vehicles -Boats');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH13', 'VEHICLE - Own  Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH2', 'VEHICLE - Own  Bulldozer');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH3', 'VEHICLE - Own  Crane');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH4', 'VEHICLE - Own  Forklift');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH5', 'VEHICLE - Own  Backhoe');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH6', 'VEHICLE - Own  Medical; Ambulance');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH7', 'VEHICLE - Own  Heavy Equipment -Other');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH8', 'VEHICLE - Own  Refrigerated');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'VEH9', 'VEHICLE - Own  Steamshovel');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WAR1', 'WAREHOUSE  -  Forklift');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WAR2', 'WAREHOUSE  -  General');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WAR3', 'WAREHOUSE  -  Management');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WIT1', 'WITH TOOLS  Unskilled - with Brooms');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WIT2', 'WITH TOOLS  Unskilled - with Carpentry Tools');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WIT3', 'WITH TOOLS  Unskilled - with Pump, Small');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WIT4', 'WITH TOOLS  Unskilled - with Saws, Chainsaw');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WIT5', 'WITH TOOLS  Unskilled - with Wheelbarrow');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WIT6', 'WITH TOOLS  Unskilled - with Yard Tools');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'WIT7', 'WITH TOOLS  Unskilled - with Other Tools');
INSERT INTO `field_options` VALUES ('opt_skill_type', 'mgr', 'Site Manager');
