<?PHP

function shn_home_view()
{ ?>

        <p><b>You called the home view action </b></p>
        <p> This is a call to view in home</p>

<?php
}

function shn_home_default()
{ ?>

    <h1 align="center">Welcome to the Sahana</h1>
    <div id="resulthome">
        <img src="theme/default/img/home_pic1.png" align="left" />
		<h2> Introducation </h2>
        <p>Sahana is an Open Source disaster management system that handles missing/displaced persons, organisation management, camp management, request management system, etc during a disaster situation.</p>
    </div>    
    
<?php
}

?>

