<?php


/**
 * Main Configuration of the Catalogue System. 
 *
 * PHP version 4 and 5
 *
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 */

/**
 * Gives the nice name of the module
 * @global string $conf['mod_service_name']
 */
 
#global $conf;

$conf['mod_service_name'] = _t("GIS Catalog service");
$conf['mod_service_menuorder'] = 17;
?>
