#!/bin/bash


rm output log
echo Removing old support files > log
echo -------------------------- >> log
echo rm output log >> log
echo ... done >> log
echo  >> log
echo Creating Administrator Entries  >> log
echo ------------------------------  >> log
echo ... >> log
psql administrator -f CreateDB.sql -o temp
cat temp >> log
echo ... done >> log
echo  >> log
echo Creating table creation file  >> log
echo ----------------------------  >> log
echo ... >> log
psql administrator -f CreateObjects.sql
echo ... done  >> log
echo  >> log
echo Creating tables  >> log
echo ---------------  >> log
echo ... >> log
psql skillsregister -f output -o temp
cat temp >> log
echo ... done >> log
echo  >> log
echo Creating permissions creation file  >> log
echo ----------------------------------  >> log
echo ... >> log
psql administrator -f CreatePermissions.sql
echo ... done  >> log
echo  >> log
echo Creating permissions  >> log
echo --------------------  >> log
echo ... >> log
psql skillsregister -f output -o temp
cat temp >> log
echo ... done >> log
echo  >> log
echo Loading data into tables >> log
echo ------------------------ >> log
echo ... >> log
psql skillsregister -f data.sql -o temp
cat temp >> log
echo ... done >> log
echo  >> log
echo PROCESS COMPLETE >> log
