<?
/**
 * @name         Search+
 * @version      0.1
 * @package      search+
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.1005
 */


$conf['mod_search+_name']         = _t("Search+");
$conf['mod_search+_menuorder']    = 200;
$conf['mod_search+_dependencies'] = "";
$conf['mod_search+_version']      = "0.1";

