<?
/**
 * @name         Report (a person)
 * @version      2.1
 * @package      report
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 * @lastModified 2012.0119
 */


$conf['mod_report_name']         = _t("Report a Person");
$conf['mod_report_menuorder']    = 11;
$conf['mod_report_version']      = 2.1;
$conf['mod_report_dependencies'] = null;


