<?php
/**
* Sahana Inventory Management System Item transfer page
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author        Mahesh Kaluarachchi <mahesh@opensource.lk>
* @copyright        Lanka Software Foundation - http://www.opensource.lk
* @package        Sahana
* @subpackage        ims
* @tutorial        
* @license          http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
*/

define(SHN_ERR_MSG_GROUP_NAME_INCOMPLETE,"Group Name is essential. Please Complete and Submit again");
define(SHN_ERR_MSG_EMAIL_MOBILE_INCOMPLETE,"E-mails or mobile numbers are is essential. Please Complete and Submit again");
define(SHN_ERR_MSG_NUMERIC_VALUE_MOBILE,"is not a numeric value");
define(SHN_ERR_MSG_EMAIL,"E-mail address is of the wrong format");
define(SHN_ERR_MSG_MESSAGE_INCOMPLETE,"Message is essential. Please Complete and Submit again");
define(SHN_ERR_MSG_KANNEL_NOT_STARTED,"Kannel has not been started. Please start kannel");