<?
/**
 * @name         PL User Services
 * @version      24
 * @package      plus
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2012.0221
 */

$conf['mod_plus_name']       = _t("Web Services");
$conf['mod_plus_menuorder']  = 99;
$conf['mod_plus_version']    = "24";
$conf['mod_plus_latest_api'] = "24";


