<?php
/**error defines of the Organization Registry 
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author     Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
* @package    sahana
* @subpackage or
*/

define(SHN_ERR_OR_NAME_INCOMPLETE,_("Organization name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_TYPE_INCOMPLETE,_("Organization Type is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_SECTOR_INCOMPLETE,_("Organization Sector is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_LOCATION_INCOMPLETE,_("Organization Location is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_UNAME_INCOMPLETE,_("User Name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_PWD_INCOMPLETE,_("Password is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_REPWD_INCOMPLETE,_("Password confirmation is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_NAME_INCOMPLETE,_("Organization name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_ADD_OPTION,_("Choose group or individual enrty."));
define(SHN_ERR_OR_ADD_TYPE,_("Select the type of the entry"));
define(SHN_ERR_OR_PREFER,_("Select the preference of form display"));
define(SHN_ERR_OR_EMAIL,_("Email address is of the wrong format"));
define(SHN_ERR_DOB_INCORRECT,_("You have to enter a Date (yyyy-mm-dd) for Date of Birth"));
?>
