<?
/**
 * @name         Error Library Constants
 * @version      1.0
 * @package      framework
 * @author       Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @link         http://sahanafoundation.org
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.0308
 */


define("SHN_AUTH_ERR_USER_EXISTS",       "User Name already taken, Please Complete and Submit again");
define("SHN_AUTH_ERR_OPENID_EXISTS",     "openID already taken, Please Complete and Submit again");
define("SHN_AUTH_ERR_PERSON_EXISTS",     "A person by that Name already exists, Please Complete and Submit again");
define("SHN_AUTH_ERR_PERSON_NOT_EXISTS", "The Person UUID does not exist, Please Complete and Submit again");
define("SHN_AUTH_ERR_UNAME_INCOMPLETE",  "User Name is essential for registration. Please Complete and Submit again");
define("SHN_AUTH_ERR_PWD_INCOMPLETE",    "Password is essential for registration. Please Complete and Submit again");
define("SHN_AUTH_ERR_REPWD_INCOMPLETE",  "Password confirmation is essential for registration. Please Complete and Submit again");
define("SHN_AUTH_ERR_REPWD_WRONG",       "Password confirmation does not match with password. Please Complete and Submit again");
define("SHN_AUTH_ERR_EMAIL_EXISTS",      "This email address is already being used by another user. Please choose another email address.");
