<?php
/**
 * @name         Arrival Rate
 * @version      1
 * @package      arrive
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine and the Sahana Foundation
 * @link         https://pl.nlm.nih.gov/about
 * @link         http://sahanafoundation.org
 * @license	 http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.1205
 */


$conf['mod_arrive_name']         = _t("Arrivals");  // Defines the name of the module
$conf['mod_arrive_menuorder']    = -10;              // Defines this module's main menu priority
$conf['mod_arrive_dependencies'] = "";
$conf['mod_arrive_version']      = 1;
