<?php
/**This is the config file for the OR module, specifies configuration
*  settings
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author     Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
* @package    sahana
* @subpackage or
*/

// provide the nice display name for the OR  module
global $conf;
$conf['mod_or_sarvodaya_name'] = _("District Offices");
$conf['mod_or_sarvodaya_start_loc'] = 1;
$conf['mod_or_sarvodaya_loc_level_start']=1;
$conf['mod_or_sarvodaya_loc_level_end']=3;
?>
