<?php

// This file is automatically generated and modified by phpMyBackupPro v.2.1

$CONF['sitename']="Uniform Server";
$CONF['lang']="english";
$CONF['ftp_use']="0";
$CONF['ftp_server']="";
$CONF['ftp_user']="";
$CONF['sql_passwd']=implode ('', file ('../mysql_password'));
$CONF['sql_host']="localhost";
$CONF['sql_user']="root";
$CONF['sql_db']="";
$CONF['ftp_passwd']="";
$CONF['ftp_path']="";
$CONF['ftp_pasv']="1";
$CONF['ftp_port']="21";
$CONF['ftp_del']="1";
$CONF['email_use']="0";
$CONF['email']="";
$CONF['stylesheet']="standard";
$CONF['date']="%x %X";
$CONF['del_time']="5";
$CONF['del_number']="7";
$CONF['timelimit']="60";
$CONF['confirm']="1";
$CONF['import_error']="1";
$CONF['no_login']="0";
$CONF['login']="0";
$CONF['dir_backup']="0";
$CONF['dir_rec']="1";

$PMBP_SYS_VAR['last_scheduled']="";
$PMBP_SYS_VAR['this_login']="05/24/07 15:41:27 (IP: 127.0.0.1)";
$PMBP_SYS_VAR['last_login']="05/24/07 15:41:24 (IP: 127.0.0.1)";
$PMBP_SYS_VAR['security_key']="9d2ca6d7e6a753957f4acf9e9f556941";
$PMBP_SYS_VAR['dir_lists']="2";
$PMBP_SYS_VAR['memory_limit']="38000000";
$PMBP_SYS_VAR['except_tables']="";
$PMBP_SYS_VAR['scheduled_debug']="0";
$PMBP_SYS_VAR['F_dbs']="";
$PMBP_SYS_VAR['F_comment']="";
$PMBP_SYS_VAR['F_tables']="1";
$PMBP_SYS_VAR['F_data']="1";
$PMBP_SYS_VAR['F_drop']="1";
$PMBP_SYS_VAR['F_compression']="";
$PMBP_SYS_VAR['F_ftp_dirs']="";
$PMBP_SYS_VAR['F_ftp_dirs_2']="";
$PMBP_SYS_VAR['EXS_scheduled_file']="???.php";
$PMBP_SYS_VAR['EXS_scheduled_dir']="FALSE";
$PMBP_SYS_VAR['EXS_period']="FALSE";
$PMBP_SYS_VAR['schedule_all_dbs']="0";
$PMBP_SYS_VAR['ftp_timeout']="10";
$PMBP_SYS_VAR['dir_email_backup']="0";
$PMBP_SYS_VAR['F_packed']="";
$PMBP_SYS_VAR['F_updates']="1";
$PMBP_SYS_VAR['F_ffadd']="1";

?>