<?php
/**error defines of the Organization Registry 
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author     Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
* @package    sahana
* @subpackage or
*/

define(SHN_ERR_OR_NAME_INCOMPLETE,"Volunteer name is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_TYPE_INCOMPLETE,"Volunteer Type is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_SECTOR_INCOMPLETE,"Volunteer Sector is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_LOCATION_INCOMPLETE,"Volunteer Location is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_UNAME_INCOMPLETE,"User Name is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_PWD_INCOMPLETE,"Password is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_REPWD_INCOMPLETE,"Password confirmation is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_NAME_INCOMPLETE,"Volunteer name is essential for registration. Please Complete and Submit again");
define(SHN_ERR_OR_ADD_OPTION,"Choose group or individual enrty.");
define(SHN_ERR_OR_ADD_TYPE,"Select the type of the entry");
define(SHN_ERR_OR_PREFER,"Select the preference of form display");
define(SHN_ERR_OR_EMAIL,"Email Address is of the wrong format");
define(SHN_ERR_DOB_INCORRECT,"You have to enter a Date (yyyy-mm-dd) for Date of Birth");

