<?php
/**error defines of the Organization Registry 
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author     Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
* @package    sahana
* @subpackage or
*/

#define(SHN_ERR_ADMIN_NAME_INCOMPLETE,"Organization name is essential for registration. Please Complete and Submit again");
define(SHN_ERR_ADMIN_LOCATION_INCOMPLETE,"Organization location is essential for registration. Please complete and submit again");
define(SHN_ERR_ADMIN_UNAME_INCOMPLETE,"User Name is essential for registration. Please complete and submit again");
define(SHN_ERR_ADMIN_PWD_INCOMPLETE,"Password is essential for registration. Please complete and submit again");
define(SHN_ERR_ADMIN_REPWD_INCOMPLETE,"Password confirmation is essential for registration. Please complete and submit again");
define(SHN_ERR_ADMIN_REPWD_WRONG,"Password and confirmation password do not match. Please complete and submit again");
#define(SHN_ERR_ADMIN_NAME_INCOMPLETE,"Organization name is essential for registration. Please Complete and Submit again");


