<li><a href="index.php?mod=admin&act=ims_config"><?=_t("Configuration");?></a></li>
<li><a href="index.php?mod=admin&act=ims_level1"><?=_t("Manage ")._lc($conf['mod_admin_ims_level1']);?></a></li>
<li><a href="index.php?mod=admin&act=ims_level2"><?=_t("Manage ")._lc($conf['mod_admin_ims_level2']);?></a></li>
<li><a href="index.php?mod=admin&act=ims_level3"><?=_t("Manage ")._lc($conf['mod_admin_ims_level3']);?></a></li>
