<?php
/**
 * @name         Statistics
 * @version      0.3
 * @package      stat
 * @author       Lan Ngoc Le <lale@mail.nih.gov>
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.1027
 */


$conf['mod_stat_name']         = _t("Statistics");
$conf['mod_stat_menuorder']    = 65;
$conf['mod_stat_version']      = 0.3;
$conf['mod_stat_dependencies'] = "";
