<?php
/**
 * @name         Statistics
 * @version      0.1
 * @package      stat
 * @author       Lan Le <lale@mail.nih.gov>
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.0711
 */

// statistics module library
global $global;
require_once($global['approot'].'/mod/lpf/lib_lpf.inc');


