<?php
/**error defines of the Inventory Management System 
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author     Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
	      Mahesh Kaluarachchi <mahesh@opensource.lk>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
* @package    sahana
* @subpackage or
*/

define(SHN_ERR_OR_NAME_INCOMPLETE,_("Inventory name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_TYPE_INCOMPLETE,_("Inventory type is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_SECTOR_INCOMPLETE,_("Inventory sector is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_LOCATION_INCOMPLETE,_("Inventory location is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_UNAME_INCOMPLETE,_("User name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_PWD_INCOMPLETE,_("Password is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_REPWD_INCOMPLETE,_("Password confirmation is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_NAME_INCOMPLETE,_("Inventory name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_ADD_OPTION,_("Choose group or individual enrty."));
define(SHN_ERR_OR_ADD_TYPE,_("Select the type of the entry"));
define(SHN_ERR_OR_PREFER,_("Select the preference of form display"));
define(SHN_ERR_OR_EMAIL,_("Email address is of the wrong format"));
define(SHN_ERR_DOB_INCORRECT,_("You have to enter a Date (yyyy-mm-dd) for date of birth"));
define(SHN_ERR_or_ims_LOCATION_INCOMPLETE,_("Location is essential for registration. Please select the location and submit again"));
define(SHN_ERR_or_ims_EMAIL,_("Invalid e-mail address"));
define(SHN_ERR_or_ims_REG_MAX,_("Your text fields should contain less than 100 characters. One of your text field has exceeded it"));
define(SHN_ERR_or_ims_ORG_EXISTS,_("'ims_inventory_records' table does not exist"));
define(SHN_ERR_IMS_TRANSFER_TABLE_EXISTS,_("ims_transfer_item table does not exist"));
define(SHN_ERR_IMS_REORDER_TABLE_EXISTS,_("ims_reorder_level table does not exist"));
define(SHN_ERR_IMS_ITEM_TABLE_EXISTS,_("ims_item_records table does not exist"));
define(SHN_ERR_IMS_RELATION_TABLE_EXISTS,_("ims_relation table does not exist"));
define(SHN_ERR_IMS_ALTERNATE_TABLE_EXISTS,_("ims_alternate table does not exist"));
define(SHN_ERR_IMS_INVENTORY_IN_USE,_("Inventory is already in use"));


define(SHN_ERR_IMS_ITEM_NAME_INCOMPLETE,_("Item name is essential. Please select an item from Add-Item main page and submit the form again"));
define(SHN_ERR_IMS_AMOUNT_INCOMPLETE,_("Amount is essential. Please complete and submit again"));
define(SHN_ERR_IMS_INVENTORY_INCOMPLETE,_("Inventory is essential. Please complete and submit again "));
define(SHN_ERR_IMS_INVALID_AMOUNT,_("The inventory doesn't have sufficient amount to transfer. Please check the amount again and resubmit the form"));
define(SHN_ERR_IMS_INVALID_DATE,_("Invalid date"));
define(SHN_ERR_IMS_AUTHORIZED_PERSON_INCOMPLETE,_("Authorized Person is essential. Please complete and submit again"));
define(SHN_ERR_IMS_DATE_INCOMPLETE,_("Date is essential. Please complete and submit again"));
define(SHN_ERR_IMS_REQUESTED_PERSON_INCOMPLETE,_("Requested person is essential. Please complete and submit again"));
define(SHN_ERR_IMS_DESTRIBUTION_METHOD_INCOMPLETE,_("Destribution method is essential. Please complete and submit again"));
define(SHN_ERR_IMS_ENTER_NUMERIC_VALUE,_("Please enter a numeric value for the amount"));
define(SHN_ERR_IMS_ENTER_NUMERIC_VALUE_COST,_("Please enter a numeric Value for the cost per unit"));
define(SHN_ERR_IMS_MANUFACTURED_DATE_INVALID,_("Expire date should be greater than Manufactured date"));

define(SHN_ERR_IMS_REORDER_VALUE_NUMERIC,_("Please enter a numeric value for item Re-Order value"));
define(SHN_ERR_IMS_INVALID_RECEIVED_AMOUNT,_("You have entered a larger amount than the amount that has been sent"));
define(SHN_ERR_IMS_UNIT_INCOMPLETE,_("Unit is essential for registration. Please complete and submit again"));
define(SHN_ERR_IMS_AMOUNT_NUMERIC,_("Please enter a positive Numeric value"));

define(SHN_ERR_IMS_TIME_AMOUNT_INCOMPLETE,_("Time amount is essential for the prediction. Please complete it and submit again"));
define(SHN_ERR_IMS_CATALOGUE_MISSING,_("Please select the catalogue that you need"));
define(SHN_ERR_IMS_INVENTORY_SEARCH_ERROR,_("Please complete either inventory name or base location"));
define(SHN_ERR_IMS_INVENTORY_ADDRESS_ERROR,_("Please enter any of the details of the owner of the inventory and submit again."));
define(SHN_ERR_IMS_ALTERNATE_ITEM_EXISTS,_("Alternete item has already been set"));
define(SHN_ERR_IMS_UNIT_MISMATCH,_("Units mismatching of selected items"));
define(SHN_ERR_IMS_RELATION_ITEM_EXISTS,_("Relation item has already been set"));


?>
