<?php
/**error defines of the Inventory Management System 
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @author     Ravindra De Silva <ravindra@opensource.lk><ravidesilva@iee.org>
	      Mahesh Kaluarachchi <mahesh@opensource.lk>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
* @package    sahana
* @subpackage or
*/

define(SHN_ERR_OR_NAME_INCOMPLETE,_t("Inventory name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_TYPE_INCOMPLETE,_t("Inventory type is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_SECTOR_INCOMPLETE,_t("Inventory sector is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_LOCATION_INCOMPLETE,_t("Inventory location is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_UNAME_INCOMPLETE,_t("User name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_PWD_INCOMPLETE,_t("Password is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_REPWD_INCOMPLETE,_t("Password confirmation is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_NAME_INCOMPLETE,_t("Inventory name is essential for registration. Please complete and submit again"));
define(SHN_ERR_OR_ADD_OPTION,_t("Choose group or individual enrty."));
define(SHN_ERR_OR_ADD_TYPE,_t("Select the type of the entry"));
define(SHN_ERR_OR_PREFER,_t("Select the preference of form display"));
define(SHN_ERR_OR_EMAIL,_t("Email address is of the wrong format"));
define(SHN_ERR_DOB_INCORRECT,_t("You have to enter a Date (yyyy-mm-dd) for date of birth"));
define(SHN_ERR_or_ims_LOCATION_INCOMPLETE,_t("Location is essential for registration. Please select the location and submit again"));
define(SHN_ERR_or_ims_EMAIL,_t("Invalid e-mail address"));
define(SHN_ERR_or_ims_REG_MAX,_t("Your text fields should contain less than 100 characters. One of your text field has exceeded it"));
define(SHN_ERR_or_ims_ORG_EXISTS,_t("'ims_inventory_records' table does not exist"));
define(SHN_ERR_IMS_TRANSFER_TABLE_EXISTS,_t("ims_transfer_item table does not exist"));
define(SHN_ERR_IMS_REORDER_TABLE_EXISTS,_t("ims_reorder_level table does not exist"));
define(SHN_ERR_IMS_ITEM_TABLE_EXISTS,_t("ims_item_records table does not exist"));
define(SHN_ERR_IMS_RELATION_TABLE_EXISTS,_t("ims_relation table does not exist"));
define(SHN_ERR_IMS_ALTERNATE_TABLE_EXISTS,_t("ims_alternate table does not exist"));
define(SHN_ERR_IMS_INVENTORY_IN_USE,_t("Inventory is already in use"));


define(SHN_ERR_IMS_ITEM_NAME_INCOMPLETE,_t("Item name is essential. Please select an item from Add-Item main page and submit the form again"));
define(SHN_ERR_IMS_AMOUNT_INCOMPLETE,_t("Amount is essential. Please complete and submit again"));
define(SHN_ERR_IMS_INVENTORY_INCOMPLETE,_t("Inventory is essential. Please complete and submit again "));
define(SHN_ERR_IMS_INVALID_AMOUNT,_t("The inventory doesn't have sufficient amount to transfer. Please check the amount again and resubmit the form"));
define(SHN_ERR_IMS_INVALID_DATE,_t("Invalid date"));
define(SHN_ERR_IMS_AUTHORIZED_PERSON_INCOMPLETE,_t("Authorized Person is essential. Please complete and submit again"));
define(SHN_ERR_IMS_DATE_INCOMPLETE,_t("Date is essential. Please complete and submit again"));
define(SHN_ERR_IMS_REQUESTED_PERSON_INCOMPLETE,_t("Requested person is essential. Please complete and submit again"));
define(SHN_ERR_IMS_DESTRIBUTION_METHOD_INCOMPLETE,_t("Destribution method is essential. Please complete and submit again"));
define(SHN_ERR_IMS_ENTER_NUMERIC_VALUE,_t("Please enter a numeric value for the amount"));
define(SHN_ERR_IMS_ENTER_NUMERIC_VALUE_COST,_t("Please enter a numeric Value for the cost per unit"));
define(SHN_ERR_IMS_MANUFACTURED_DATE_INVALID,_t("Expire date should be greater than Manufactured date"));

define(SHN_ERR_IMS_REORDER_VALUE_NUMERIC,_t("Please enter a numeric value for item Re-Order value"));
define(SHN_ERR_IMS_INVALID_RECEIVED_AMOUNT,_t("You have entered a larger amount than the amount that has been sent"));
define(SHN_ERR_IMS_UNIT_INCOMPLETE,_t("Unit is essential for registration. Please complete and submit again"));
define(SHN_ERR_IMS_AMOUNT_NUMERIC,_t("Please enter a positive Numeric value"));

define(SHN_ERR_IMS_TIME_AMOUNT_INCOMPLETE,_t("Time amount is essential for the prediction. Please complete it and submit again"));
define(SHN_ERR_IMS_CATALOGUE_MISSING,_t("Please select the catalogue that you need"));
define(SHN_ERR_IMS_INVENTORY_SEARCH_ERROR,_t("Please complete either inventory name or base location"));
define(SHN_ERR_IMS_INVENTORY_ADDRESS_ERROR,_t("Please enter any of the details of the owner of the inventory and submit again."));
define(SHN_ERR_IMS_ALTERNATE_ITEM_EXISTS,_t("Alternete item has already been set"));
define(SHN_ERR_IMS_UNIT_MISMATCH,_t("Units mismatching of selected items"));
define(SHN_ERR_IMS_RELATION_ITEM_EXISTS,_t("Relation item has already been set"));


?>
