<?
/**
 * @name         Resources
 * @version      1.2
 * @package      rez
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.0308
 */


$conf['mod_rez_name']         = _t("Resources");
$conf['mod_rez_menuorder']    = 20;
$conf['mod_rez_dependencies'] = "";
$conf['mod_rez_version']      = "1.2";
