<h2>NOW CONSIDER THE TORTOISE AND the eagle.</h2>
<p>
The tortoise is a ground-living creature. It is impossible to live nearer the ground without being under it. Its horizons are a few inches away. It has about as good a turn of speed as you need to hunt down a lettuce. It has survived while the rest of evolution flowed past it by being, on the whole, no threat to anyone and too much trouble to eat.
<br>
   And then there is the eagle. A creature of the air and high places, whose horizons go all the way to the edge of the world. Eyesight keen enough to spot the rustle of some small and squeaky creature half a mile away. All power, all control. Lightning death on wings. Talons and claws enough to make a meal of anything smaller than it is and at least take a hurried snack out of anything bigger.
<br>
   And yet the eagle will sit for hours on the crag and survey the kingdoms of the world until it spots a distant movement and then it will focus, focus, focus on the small shell wobbling among the bushes down there on the desert. And it will leap . . .
<br>
   And a minute later the tortoise finds the world dropping away from it. And it sees the world for the first time, no longer one inch from the ground but five hundred feet above it, and it thinks: what a great friend I have in the eagle.
<br>
  And then the eagle lets go.<br>
  And almost always the tortoise plunges to its death. Everyone knows why the tortoise does this. Gravity is a habit that is hard to shake off. No one knows why the eagle does this. There's good eating on a tortoise but,considering the effort involved, there's much better eating on practically anything else. It's simply the delight of eagles to torment tortoises.<br>
  But of course, what the eagle does not realize is that it is participating in a very crude form of natural selection.<br>
One day a tortoise will learn how to fly.
</p>

