<?php
/* $Id; */

/**
* CMS Home page
*
* PHP version 4 and 5
*
* LICENSE: This source file is subject to LGPL license
* that is available through the world-wide-web at the following URI:
* http://www.gnu.org/copyleft/lesser.html
*
* @package    Sahana - http://sahana.sourceforge.net
* @author   Chathra Hendehewa <chathra@opensource.lk>
* @author   Mifan Careem <mifan@opensource.lk>
* @copyright  Lanka Software Foundation - http://www.opensource.lk
*/

function shn_cms_default(){
?>
<h1><?php echo _t("Camp Management System"); ?></h1>
<div id="home">
	<img src="theme/default/img/cms.png" align="center" />
	<ul>
   	<li>The Camps Management System is a System to Manage Camps</li>
	  <br>
		<li>It helps coordinate and track people, inventory and activities within camps</li>
		<br>
		<li>It also provides facilities to get Reports and  Statistics of camps</li>
		<br>
	</ul>
						 
<?php 
}