<?
/**
 * @name         Report a Person
 * @version      1.2
 * @package      rap
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.0325
 */


$conf['mod_rap_name']         = _t("Report a Person 1");  // Defines the name of the module
$conf['mod_rap_menuorder']    = 10;                      // Defines this module's main menu priority
$conf['mod_rap_dependencies'] = "pop(1.0)";
$conf['mod_rap_version']      = 1.2;
