<?php

/**
 * 
 * This file represents the reports  of the DVR module
 * PHP version 4 and 5
 *
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 *
 * @author	   Isuru Samaraweera 
 * @copyright  Lanka Software Foundation - http://www.opensource.lk
 * @package    module
 * @subpackage dvr
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 *
 */
function _shn_drill_downby_group() {
?>
 	 
   	 <div id ="result">
	<table>
        <thead>
        		<td></td>
            <td><?=_("Group Type")?></td>
            <td><?=_("Group Head Name")?></td>
            <td><?=_("Family Name")?></td>
            <td><?=_("Local Name")?></td>
          	<td><?=_("NIC")?></td>
            <td><?=_("Address")?></td>
         <td><a href='index.php?mod=dvr&act=add_new_indv'>Edit</a></td>
        </thead>
        <table>
        </div>
   <?php


}

function _shn_drill_downby_shelter() {
?>
 	 
   	 <div id ="result">
	<table>
        <thead>
        		<td></td>
            <td><?=_("Group Type")?></td>
            <td><?=_("Group Head Name")?></td>
            <td><?=_("Family Name")?></td>
            <td><?=_("Local Name")?></td>
          	<td><?=_("NIC")?></td>
            <td><?=_("Address")?></td>
         <td><a href='index.php?mod=dvr&act=add_new_indv'>Edit</a></td>
        </thead>
        <table>
        </div>
   <?php


}

function _shn_drill_downby_incident() {
?>
 	 
   	 <div id ="result">
	<table>
        <thead>
        		<td></td>
            <td><?=_("Group Type")?></td>
            <td><?=_("Group Head Name")?></td>
            <td><?=_("Family Name")?></td>
            <td><?=_("Local Name")?></td>
          	<td><?=_("NIC")?></td>
            <td><?=_("Address")?></td>
         <td><a href='index.php?mod=dvr&act=add_new_indv'>Edit</a></td>
        </thead>
        <table>
        </div>
   <?php


}
?>
