<?
/**
 * @name         Home
 * @version      1.0
 * @package      home
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.0328
 */


$conf['mod_home_name']         = _t("Home");
$conf['mod_home_menuorder']    = 200;
$conf['mod_home_dependencies'] = "";
$conf['mod_home_version']      = "1.0";

