<?php
/**
 * @name         Event Manager
 * @version      1.1
 * @package      em
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine
 * @link         https://pl.nlm.nih.gov/about
 * @license	 http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 * @lastModified 2011.0302
 */

$conf['mod_em_name']         = _t("Event Manager");  // Defines the name of the module
$conf['mod_em_menuorder']    = 90;                   // Defines this module's main menu priority
$conf['mod_em_dependencies'] = "";
$conf['mod_em_version']=0.1;

//$conf['mod_em_hide_in_menu'] = true;