<?php
/**
 * REG Module
 *
 * PHP version >=5
 *
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 *
 * @author     Greg Miernicki <g@miernicki.com>
 * @package    module ha
 * @version    1.0
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 *
 */


$conf['mod_ha_name']         = _t("Hospital Administration");   // Defines the name of the module
$conf['mod_ha_menuorder']    =  75;                              // Defines this module's main menu priority 
$conf['mod_ha_dependencies'] = "";
$conf['mod_ha_version']=1.0;
