<table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr>
        <td width="60" valign="top"><img src="images/gov.gif"></td>
        <td valign="top" bgcolor="#FFFFFF">&nbsp;</td>
        <td valign="top"><div align="right"><img src="images/cnologo.gif" width="382" height="70"></div></td>
    </tr>
    <tr>
        <td class="formTitle" bgcolor="#42426F" colspan="3"><center><font size="4">Damage Registry<font></center></td>
    </tr>
</table>