#!/bin/bash
USER='root'
PASS=''
HOST='localhost'
DATABASE='sahana'

function loadsql() {
    echo "Loading SQL script $1"
    mysql $DATABASE -h $HOST -u $USER -p $PASS < $1
}

# Basic structure
echo "Createing Skeletal database with mysql-dbcrete.sql"
mysql -h $HOST -u $USER -p $PASS < mysql-dbcreate.sql

# other main tables
loadsql mysql-acl.sql 

# configuration details
loadsql mysql-config.sql

# Modules
loadsql ../mod/rms/ins/rms.sql

# Sample data
loadsql mysql-sampledata.sql



