#!/bin/bash
USER='root'
PASS=''
HOST='localhost'
DATABASE='sahana'

function loadsql() {
    echo "Loading SQL script $1"
    if [ "$PASS" = '' ]; then
        mysql $DATABASE -h $HOST -u $USER < $1
    else
        mysql $DATABASE -h $HOST -u $USER -p$PASS < $1
    fi
}

# Basic structure
loadsql mysql-dbcreate.sql

# other main tables
loadsql mysql-acl.sql 

# configuration details
loadsql mysql-config.sql

# Modules
loadsql ../mod/rms/ins/rms.sql

# Sample data
loadsql mysql-sampledata.sql



