<?php
/**
 * @name         Administration
 * @version      11
 * @package      admin
 * @author       Greg Miernicki <g@miernicki.com> <gregory.miernicki@nih.gov>
 * @about        Developed in whole or part by the U.S. National Library of Medicine and the Sahana Foundation
 * @link         https://pl.nlm.nih.gov/about
 * @link         http://sahanafoundation.org
 * @license	 http://www.gnu.org/licenses/lgpl-2.1.html GNU Lesser General Public License (LGPL)
 * @lastModified 2012.0208
 */

define("SHN_ERR_ADMIN_LOCATION_INCOMPLETE","Organization location is essential for registration. Please complete and submit again");
define("SHN_ERR_ADMIN_UNAME_INCOMPLETE",   "User Name is essential for registration. Please complete and submit again");
define("SHN_ERR_ADMIN_PWD_INCOMPLETE",     "Password is essential for registration. Please complete and submit again");
define("SHN_ERR_ADMIN_REPWD_INCOMPLETE",   "Password confirmation is essential for registration. Please complete and submit again");
define("SHN_ERR_ADMIN_REPWD_WRONG",        "Password and confirmation password do not match. Please complete and submit again");
define("SHN_ERR_ADMIN_NAME_INCOMPLETE",    "Organization name is essential for registration. Please Complete and Submit again");


