<?php
/* $Id */

/**
 * Main Configuration of the User Preferences
 *
 * PHP version 4 and 5
 *
 * LICENSE: This source file is subject to LGPL license
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 *
 * @author     Janaka Wickramasinghe <janaka@opensource.lk>
 * @copyright  Lanka Software Foundation - http://www.opensource.lk
 * @package    module
 * @subpackage pref 
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL)
 *
 */


/**
 * Gives the nice name of the module
 * @global string $conf['mod_pref_name']
 */
$conf['mod_pref_name'] = _t("User Preferences");
$conf['mod_pref_menuorder'] = 19;
$conf['mod_pref_dependencies'] = "";

